version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongodb
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo
    networks:
      - auth-network
    volumes:
      - mongo-gatchadb:/data/db
  auth-api:
    depends_on:
      - mongo
    container_name: auth-api
    build: .
    image: auth-api:latest
    environment:
      SPRING_DATA_MONGO_URI: mongodb://mongoadmin:password@localhost:27017/authdb
    ports:
      - "8080:8080"
    networks:
      - auth-network
networks:
  auth-network:
    driver: bridge
volumes:
    mongo-gatchadb: